name: "Dependabot PR Security Compliance (Maven)"

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_dispatch: #Add this manual dispatch

jobs:
  security_compliance:
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust to match your project's Java version

      - name: Install OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Maven Security Audit"
          scan: "."
          format: "ALL"

      - name: Run Maven License Check
        run: |
          mvn org.codehaus.mojo:license-maven-plugin:2.0.0:download-licenses
        continue-on-error: false

      # Optional: Generate SBOM
      - name: Generate SBOM (CycloneDX)
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom -DskipTests
