name: "Dependabot PR Security Compliance (Maven)"

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  security_compliance:
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Set up Java
      #  id: setup-java
      #  uses: actions/setup-java@v4
      #  with:
      #    distribution: 'temurin'
      #    java-version: '17'


      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Maven Security Audit"
          path: "."
          format: "ALL"
          out: "dependency-check-report"

      - name: Upload OWASP Dependency Check Report
        uses: actions/upload-artifact@main
        with:
          name: dependency-check-report
          path: dependency-check-report/

      - name: Run Maven License Check
        run: |
          mvn org.codehaus.mojo:license-maven-plugin:2.0.0:download-licenses
        continue-on-error: false

      - name: Generate SBOM (CycloneDX)
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom -DskipTests
